### ISSUE TITLE
About Data processing

### ISSUE THREAD

**Issue by aonihao1** [alexandrosstergiou/progressive-action-prediction#4]
Hello, I would like to ask you some questions. In the part of video data processing, I use UCF-101 data set, how to use the script? I didn't understand the official information.The part I don't know how to manipulate is here:
................................................................................................................................................
A custom format is used for the train/val label files of each datasets:
**This can be done through the scripts provided in labels**
( If I use the ucf101 dataset, how do I generate labels using scripts? What do time_start and time_end mean here?)
We have tested our code over the following datasets:
Conversion of videos to SQLite3

(How to convert a video to SQLite3? Sorry I'm so stupid, but I really want to use your code.)
Instead of extracting video frames stored as image files (//etc.) that dramatically increase the number of inodes use, we use files for each video and store frames as BLOBS..png.jpeg.db
You can use the pypi [package](https://pypi.org/project/dataset2database/) or [repo](https://github.com/alexandrosstergiou/dataset2database) to convert video files to SQL:dataset2databse
..............................................................................................................................................................................................................................
I don't know much about the code, and I really hope to get your help. I really appreciate it，Looking forward to your reply! If possible, I hope to have your contact information, wechat or ins, etc

**Comment by alexandrosstergiou** [comment]
Hi @ya-92626 , the latest commit loads video files and folders containing frames directly. So you can instead use this if you weren't able to store videos as SQL blobs.
