### ISSUE TITLE
Are all test splits from UCF-101 are used in evaluation?

### ISSUE THREAD

**Issue by ee2110** [alexandrosstergiou/progressive-action-prediction#6]
Hi, thank you for the great work! I was wondering if you are using all the 3 test splits given in UCF-101 dataset during evaluation. I have read the paper but didn't find it, therefore, it would be great if you could advise us. Thank you!

**Comment by alexandrosstergiou** [comment]
Hi @ee2110 , the reported results are averaged over the 3 UCF-101 test spits. The checkpoints provided are for split1
