### ISSUE TITLE
Request to release pretrained models for training 

### ISSUE THREAD

**Issue by vikrant-at-honda** [alexandrosstergiou/progressive-action-prediction#9]
Hi @alexandrosstergiou ,

Since I was not able to reproduce the results from the checkpoint model you have shared, I would like to train the model myself. 
For that I am lacking the pretrained model used by you. It would be really helpful if you could release the same. 

Thank you so much.

**Comment by alexandrosstergiou** [comment]
Closing as this was primarily related to using UCF101 subsets (which have different class indices). There was also an offline discussion by email which hopefully helped resolve the issues.
For anyone else interested, the pretrained encoders are part of the publically available models, so to drain from scratch only load the encoder weights (and not TemPr)
